const CACHE='meu-controle-v2-24';
const ASSETS=[
  './','./index.html','./style.css','./app.js','./mobile-launches.js','./mobile-agenda.js','./mobile-settings.js','./profile-flex.js','./navigation-state.js','./firebase-bridge.js','./sync-diagnostic.js','./sync-canary.js','./sync-v03.js','./sync-compare.js','./sync-diff.js','./sync-import-v06.js','./sync-plan-v07.js','./sync-batch-v08.js','./manifest.json',
  './favicon.png','./apple-touch-icon.png','./app-icon.svg','./logo-horizontal.svg',
  './icons/icon-72.png','./icons/icon-96.png','./icons/icon-144.png','./icons/icon-192.png','./icons/icon-512.png'
];
const FONT_LINKS=`<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">`;
const SCRIPTS=['profile-flex.js','navigation-state.js','firebase-bridge.js','sync-diagnostic.js','sync-canary.js','sync-v03.js','sync-compare.js','sync-diff.js','sync-import-v06.js','sync-plan-v07.js','sync-batch-v08.js'];
const MODULE_SCRIPTS=['firebase-bridge.js','sync-canary.js','sync-v03.js','sync-compare.js','sync-diff.js','sync-import-v06.js','sync-plan-v07.js','sync-batch-v08.js'];
const JS_FIX=`\n/* V2.24 — atualização confiável do PWA */\n(function(){try{if('serviceWorker' in navigator)navigator.serviceWorker.getRegistration().then(r=>r&&r.update()).catch(()=>{})}catch{}try{const originalUpdateInstallUI=updateInstallUI;updateInstallUI=function(){const btn=$('installAppBtn'),title=$('installStatusTitle'),text=$('installStatusText');if(!btn||!title||!text)return;const standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;if(standalone){title.textContent='Meu Controle instalado ✓';text.textContent='Você já está usando o app instalado neste computador.';btn.textContent='Aplicativo instalado';btn.disabled=true;const help=document.querySelector('.install-help');if(help)help.textContent='Instalação concluída. O Meu Controle abre em janela própria como aplicativo.';return}originalUpdateInstallUI()};const refresh=()=>setTimeout(updateInstallUI,250);window.addEventListener('load',refresh);window.addEventListener('focus',refresh);try{window.matchMedia('(display-mode: standalone)').addEventListener('change',refresh)}catch{}setTimeout(updateInstallUI,700)}catch{}})();\n`;
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('meu-controle-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
async function cachePut(request,response){try{const cache=await caches.open(CACHE);await cache.put(request,response.clone())}catch{}return response}
async function htmlWithMerriweather(request){try{const response=await fetch(request,{cache:'no-store'});if(!response.ok)throw new Error('network');let html=await response.text();if(!html.includes('fonts.googleapis.com/css2?family=Merriweather'))html=html.replace('</head>',`${FONT_LINKS}</head>`);for(const s of SCRIPTS){if(!html.includes(s)){const type=MODULE_SCRIPTS.includes(s)?' type="module"':'';html=html.replace('</body>',`<script${type} src="./${s}"></script></body>`)}}const headers=new Headers(response.headers);headers.set('content-type','text/html; charset=utf-8');headers.set('cache-control','no-store');const fresh=new Response(html,{status:response.status,statusText:response.statusText,headers});await cachePut(new Request('./index.html',{method:'GET'}),fresh.clone());return fresh}catch{return(await caches.match('./index.html'))||Response.error()}}
async function freshAppJs(request){try{const response=await fetch(request,{cache:'no-store'});if(!response.ok)throw new Error('network');let text=await response.text();text=text.replace("window.addEventListener('beforeinstallprompt',e=>{\n  e.preventDefault();\n  deferredInstallPrompt=e;\n  updateInstallUI();\n});","window.addEventListener('beforeinstallprompt',e=>{\n  // Mantém a promoção nativa do navegador e também registra a oferta para instalação manual.\n  deferredInstallPrompt=e;\n  updateInstallUI();\n});");const fresh=new Response(text+JS_FIX,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-store'}});await cachePut(request,fresh.clone());return fresh}catch{return(await caches.match(request))||Response.error()}}
async function networkFirst(request){try{const response=await fetch(request,{cache:'no-store'});if(!response.ok)throw new Error('network');return cachePut(request,response)}catch{return(await caches.match(request))||(await caches.match('./index.html'))||Response.error()}}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const url=new URL(e.request.url);if(e.request.mode==='navigate'&&url.origin===self.location.origin&&url.pathname.startsWith('/MeuControle/')){e.respondWith(htmlWithMerriweather(e.request));return}if(url.origin===self.location.origin&&url.pathname.endsWith('/app.js')){e.respondWith(freshAppJs(e.request));return}if(url.origin===self.location.origin){e.respondWith(networkFirst(e.request));return}e.respondWith(fetch(e.request).catch(()=>caches.match(e.request)))});
