/* MeuControle — V0.5.1: lupa de divergências reais local x nuvem, somente leitura */
import { collection, getDocs } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
(()=>{
 if(window.__meuControleSyncDiffLoaded)return;window.__meuControleSyncDiffLoaded=true;
 const KEY='meu_controle_entries_v2';
 const local=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
 const cloud=()=>window.MeuControleCloud||null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clean=o=>{const x=JSON.parse(JSON.stringify(o||{}));delete x._syncTest;delete x.syncMeta;return x};
 const flat=(o,p='',r={})=>{if(o&&typeof o==='object'&&!Array.isArray(o)){Object.keys(o).sort().forEach(k=>flat(o[k],p?`${p}.${k}`:k,r));}else r[p]=o;return r};
 const show=v=>v===undefined?'—':v===null?'null':typeof v==='object'?JSON.stringify(v):String(v);
 function root(){return document.querySelector('#settingsPage .sync-compare-box')}
 function ensure(){const r=root();if(!r)return;let b=r.querySelector('.sync-diff-box');if(b)return b;
  const st=document.createElement('style');st.textContent=`.sync-diff-box{display:none;margin-top:9px;padding-top:9px;border-top:1px solid #e1e8e4}.sync-diff-box.show{display:block}.sync-diff-title{display:flex;justify-content:space-between;gap:8px;align-items:center;font-size:10px;font-weight:800}.sync-diff-select{width:100%;margin-top:7px;min-height:34px}.sync-diff-table{margin-top:8px;display:grid;gap:5px}.sync-diff-row{padding:7px;border-radius:8px;background:#f6f8f7;font-size:9px;overflow-wrap:anywhere}.sync-diff-field{font-weight:800;color:#164f78;margin-bottom:4px}.sync-diff-values{display:grid;grid-template-columns:1fr 1fr;gap:6px}.sync-diff-values span{display:block;padding:5px;border-radius:6px;background:white}.sync-diff-note{margin-top:7px;font-size:9px;color:#6b766f}.sync-diff-empty{margin-top:8px;padding:8px 9px;border-radius:9px;background:#eef7f0;color:#386245;font-size:9px;line-height:1.4}`;document.head.appendChild(st);
  b=document.createElement('div');b.className='sync-diff-box';b.innerHTML=`<div class="sync-diff-title"><span>Lupa da divergência</span><span class="sync-compare-pill">V0.5.1 · leitura</span></div><select class="sync-diff-select"></select><div class="sync-diff-table"></div><div class="sync-diff-empty"></div><div class="sync-diff-note">Somente leitura: metadados técnicos de sincronização são ignorados e nenhum campo é alterado.</div>`;r.appendChild(b);return b}
 async function inspect(){const b=ensure(),c=cloud(),u=c?.currentUser?.();if(!b||!c?.db||!u)return;try{const ls=local(),snap=await getDocs(collection(c.db,'users',u.uid,'entries')),rm=new Map(snap.docs.map(d=>[d.id,d.data()]));const diffs=[];ls.filter(e=>e?.id&&rm.has(e.id)).forEach(e=>{const a=flat(clean(e)),z=flat(clean(rm.get(e.id))),keys=[...new Set([...Object.keys(a),...Object.keys(z)])].sort(),rows=keys.filter(k=>JSON.stringify(a[k])!==JSON.stringify(z[k])).map(k=>({k,a:a[k],b:z[k]}));if(rows.length)diffs.push({e,rows})});
  const sel=b.querySelector('select'),table=b.querySelector('.sync-diff-table'),empty=b.querySelector('.sync-diff-empty');b.classList.add('show');
  if(!diffs.length){sel.style.display='none';table.innerHTML='';empty.style.display='block';empty.textContent='Nenhuma divergência real encontrada ✓ Os dados do lançamento são iguais; diferenças técnicas de sincronização foram ignoradas.';return}
  empty.style.display='none';sel.style.display='block';sel.innerHTML=diffs.map((x,i)=>`<option value="${i}">${esc(x.e.description||x.e.title||x.e.id)} · ${x.rows.length} campo(s)</option>`).join('');const render=()=>{const x=diffs[Number(sel.value)||0];table.innerHTML=x.rows.map(d=>`<div class="sync-diff-row"><div class="sync-diff-field">${esc(d.k)}</div><div class="sync-diff-values"><span><b>Local</b><br>${esc(show(d.a))}</span><span><b>Nuvem</b><br>${esc(show(d.b))}</span></div></div>`).join('')};sel.onchange=render;render()}catch(e){console.warn('V0.5.1 diff',e)}}
 document.addEventListener('click',e=>{if(e.target.closest('.sync-compare-run'))setTimeout(inspect,900)});window.addEventListener('load',()=>setTimeout(ensure,900));window.MeuControleSyncDiff={inspect,readOnly:true,version:'0.5.1'};
})();
